server:
  port: 8000

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          public-client:
            registration:
              client-id: "public-client"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "http://localhost:3000/callback"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
            require-proof-key: true
